title = "The Stillsands Gauntlet Run"
type = 'gauntlet-run'
location = 'The Stillsands'

requires = [
    'story/the-sea-of-sands',
]

unlocks = [
    'weapon/carjas-bane',
]


begin = 'Win the race, speak to Nil'
