title = "Cradle of Echoes"
type = 'story'
start = 'The Base'
end = 'The Base'

unlocks = [
    'story/completed-subfunctions',

    'side-quest/the-second-verse',
    'side-quest/the-valley-of-the-fallen',

    'gauntlet-run/dry-yearn',
]


begin = 'Watch the fight, then explore the area'

[[action]]
text = 'Go into the research lab, get Beta out of the capsule'

[[action]]
text = 'Defeat the Specter in the lab'

[[action]]
text = 'Defeat the Specter outside (get the cannon from the dead Ravager)'

[[action]]
text = 'Talk to Beta'
