title = "Death's Door"
type = 'story'
start = "Sylens' Workshop"
end = "Stone's Echo"

unlocks = [
    'story/the-dying-lands',

    'side-quest/the-burning-blooms',

    'weapon/frost-hunter-bow',
    'armour/carja-shadow',
]


begin = 'Approach the Metal Devil, look around, activate the console, scan datapoints'

[[action]]
text = 'Follow the trail, ensure you get/already have a Scrapper circulator, keep an eye out for foxes for pouch upgrade materials'

[[action]]
text = 'Buy the Frost Hunter Bow from the Hunter on the way'

[[action]]
text = 'Talk to Hades, then Sylens to get the igniter recipe'

[[action]]
text = 'Kill leaplashers, craft igniter and upgrade anything that can be'

[[action]]
text = 'Use igniter, work your way inside, get Gaia'

[[action]]
text = 'Avoid Erik as much as possible once proving his shield is impervious'

[[action]]
text = 'Escape Latopolis'

