title = "Faro's Tomb"
type = 'story'
start = 'The Base'
end = "Legacy's Landfall"

unlocks = [
    'story/faros-tomb-thebes',

    'side-quest/the-way-home',
    'errand/the-souvenir',
    'errand/tides-of-justice',

    'weapon/thunderbolt-shredder-gauntlet',

    'tallneck/landfall',
]

begin = "After leaving the Base, Kotallo tells you to go to Fall's Edge"

[[action]]
text = "Leave Fall's Edge, travel by boat to the Isle of Spires"

[[action]]
text = 'Collect the Thunderbolt Shredder Gauntlet from the superior cache'
location = "Legacy's Landfall"
