title = "Gemini"
type = 'story'
start = 'The Base'
end = "Tilda's Mansion"

triggers = 'story/all-that-remains'

unlocks = [
    'side-quest/forbidden-legacy',
]


begin = 'Talk to Beta, then Gaia'

[[action]]
text = 'Kill the Behemoth and Ravager'
location = 'Gemini'

[[action]]
text = 'Proceed through the cauldron, killing the other machines'

[[action]]
text = 'Kill the slaughterspine at the core, return to Varl and Beta'
