title = "Reach For The Stars"
type = 'story'
start = 'Far Zenith'
end = 'Meridian'

triggers = 'story/the-point-of-the-lance'

autobegin = true

[[action]]
text = 'Explore Far Zenith launch facility'

[[action]]
text = 'Find Zero Dawn Trade Agreement datapoint on table'

[[action]]
text = 'Use Slitherfang coil blasters (on the ground, to the left, once fire goes out)'
