title = 'Restored Gaia'
type = 'marker'
location = 'The Base'

unlocks = [
    'story/the-broken-sky',
    'story/the-sea-of-sands',
    'story/seeds-of-the-past',

    'side-quest/a-tribe-apart',
    'side-quest/breaking-even',
    'side-quest/signal-spike',
    'side-quest/the-deluge',
    'side-quest/the-promontory',
    'side-quest/thirst-for-the-hunt',
    'errand/the-oldgrowth',
    'errand/supply-drop',
    'errand/a-hunt-to-remember',
    'errand/the-taste-of-victory',
    'errand/sons-of-prometheus-data',

    'black-box/bleeding-mark',
    'black-box/bonewhite-tear',
    'black-box/isle-of-spires',
    'black-box/salt-bite',
    'black-box/the-memorial-grove',
    'black-box/the-raintrace',
    'black-box/the-stand-of-the-sentinels',
    'black-box/the-stillsands',
    'cauldron/chi',
    'cauldron/kappa',
    'gauntlet-run/dry-yearn',
    'melee-pit/scalding-spear',
    'melee-pit/thornmarsh',
    'rebel-camp/breached-rock',
    'rebel-camp/devils-grasp',
    'rebel-camp/fenrise',
    'rebel-camp/first-forge',
    'rebel-camp/the-hive',
    'rebel-outpost/dry-yearn',
    'rebel-outpost/the-high-turning',
    'rebel-outpost/stillsands-north',
    'rebel-outpost/stillsands-south',
    'rebel-outpost/stillsands-west',
    'rebel-outpost/bonewhite-tear',
    'rebel-outpost/runners-wild',
    'rebel-outpost/shining-wastes-north',
    'rebel-outpost/shining-wastes-south',
    'rebel-outpost/raintrace-north',
    'rebel-outpost/raintrace-east',
    'rebel-outpost/raintrace-west',
    'rebel-outpost/the-stand-of-the-sentinels',
    'rebel-outpost/the-graypeak',
    'salvage/the-greenswell',
    'salvage/the-raintrace',
    'salvage/the-stillsands',
    'tallneck/the-stillsands',
    'tallneck/the-stand-of-the-sentinels',

    'weapon/purgewater-hunter-bow',
    'weapon/elite-ropecaster',
    'armour/nora-valiant',
]

begin = 'RESTORED GAIA'
