title = "Seeds of the Past"
type = 'story'
location = 'The Greenhouse'

unlocks = [
    'story/cradle-of-echoes',

    'side-quest/in-the-fog',
    'errand/the-music-in-metal',
]

after = [
    'story/the-sea-of-sands',
    'story/the-kulrut',
]


begin = 'Approach the Greenhouse, kill the Quen marines'

[[action]]
text = 'Explore the Greenhouse, meet Alva'

[[action]]
text = 'Continue exploring the Greenhouse, kill the Dreadwing, equip the Vine Cutter, get Demeter'

[[action]]
text = 'Return Demeter to the Base'
