title = "Singularity"
type = 'story'
start = 'The Base'
end = 'The Base'

unlocks = [
    'completing-the-game',
]

begin = 'Talk to Sylens and Tilda, then exit the base and go to the beach'

[[action]]
text = 'Infiltrate the base, killing Specters along the way'

[[action]]
text = 'Kill Erik'

[[action]]
text = 'Kill Tilda'

[[action]]
text = 'Talk to everyone one last time, then go sit with Varl'
