title = "The Kulrut"
type = 'story'
location = 'Memorial Grove'

unlocks = [
    'story/cradle-of-echoes',

    'side-quest/the-valley-of-the-fallen',
    'side-quest/blood-for-blood',
    'errand/in-bloom',
    'errand/opening-the-arena',
]

after = [
    'weapon/icefire-blastsling',    # upgrade this for the Slitherfang
]


begin = 'Talk to Hekarro and Tekotteh'

[[action]]
text = 'Follow Dekka, battle machines'

[[action]]
text = 'Kill the Slitherfang, luring it away from the ballista so it can fire'

[[action]]
text = 'Kill the rebel forces, drive Regalla away'

[[action]]
text = 'Get Aether, rewatch the holograms, talk to Dukkah and Kalla and unlock the arena'

[[action]]
text = 'Return Aether to The Base'
