title = "The Point of the Lance"
type = 'story'
start = 'Meridian'
end = 'The Lift'

triggers = 'story/to-the-brink'

autobegin = true

[[action]]
text = 'Examine Hades sphere'

[[action]]
text = 'Talk to Avad, learn about Fashav'

[[action]]
text = 'Talk to everyone else'
