title = "The Wings of The Ten"
type = 'story'
start = 'The Base'
end = 'Memorial Grove'

unlocks = [
    'story/singularity',

    'errand/shining-example',
]

begin = 'Enter the Base, talk to companions about Tilda'

[[action]]
text = 'Talk to Zo outside the east exit'

[[action]]
text = 'Craft Sunwing override, climb the mountain, get a Sunwing'

[[action]]
text = 'Override the Tallneck, get a bomb, drop the bomb'

[[action]]
text = 'Duff up Regalla, then spare her life'
