title = "The Embassy"
type = 'story'
start = 'Barren Light'
end = "No Man's Land"

unlocks = [
    'story/deaths-door',
]

begin = 'Speak to Erend'

[[action]]
text = 'Speak to Lawan, get introduced to Nozar'

[[action]]
text = 'Follow Varl to the Embassy, exhaust Fashav diaglogue'

[[action]]
text = 'Regalla attacks, take out four riders to trigger cutscene'

[[action]]
text = 'Take out four more riders to trigger cutscene'

[[action]]
text = "Break Grudda's shield, then kill him"

[[action]]
text = 'Speak to Lawan'
