title = "The Sea of Sands"
type = 'story'
start = 'The Stillsands'
end = 'The Stillsands'

unlocks = [
    'story/cradle-of-echoes',

    'side-quest/boom-or-bust',
    'side-quest/lofty-ambitions',
    'errand/broken-locks',
    'errand/nights-of-lights',
    'errand/burden-of-command',
]

finish_before = [
    'side-quest/drowned-hopes',
]

begin = 'Talk to the Oseram, dive to get the mask'

[[action]]
text = 'Fetch the parts from the machine herd'

[[action]]
text = 'Explore the underwater area, and drain it'

[[action]]
text = 'Kill the Tideripper'

[[action]]
text = 'Retrieve Poseidon'

[[action]]
text = 'Return Poseidon to the Base'
