title = "The Dying Lands"
type = 'story'
start = "Stone's Echo"
end = 'Repair Bay Tau'

unlocks = [
    'story/the-dying-lands-plainsong',
    'side-quest/the-burning-blooms',
]


begin = "Remove the Plowhorn's damaged part, convince Varl to follow Zo"
