title = "The Eye of the Earth"
type = 'story'
start = 'Repair Bay Tau'
end = 'The Base'

unlocks = [
    'story/restored-gaia',
]


autobegin = true

[[action]]
text = 'Figure out the way in, insert Gaia kernel into the console'

[[action]]
text = 'Explore the base, use the Fabrication Terminal to finish any corrupted overrides'

[[action]]
text = 'Exit the base and speak to Rukka to get the rumour about of The Hive'
