title = "The Broken Sky"
type = 'story'
location = 'Memorial Grove'

unlocks = [
    'story/the-broken-sky-bulwark',

    'weapon/cleaving-sharpshot-bow',
]

after = [
    'story/the-sea-of-sands',
]


begin = 'Tour the Memorial Grove with Dekka, then speak to Hekarro'
