title = 'To The Brink'
type = 'story'
start = 'The Lift'
end = 'The Daunt'
autobegin = true

unlocks = [
    'story/to-the-brink-erend',

    'side-quest/deep-trouble',
    'side-quest/the-bristlebacks',
    'encounter/telga-fendur',

    'relic-ruin/the-daunt',
    'hunting-ground/the-daunt',
    'vista-point/the-daunt',
    'melee-pit/chainscrape',
    'errand/learning-machine-strike',

    'pouch/potion-pouch',
    'pouch/resource-pouch',
    'pouch/trap-pouch',
    'pouch/bomb-satchel',
    'weapon/frost-blastsling',
    'weapon/hunter-bow',
]

[[action]]
text = 'Take the lift down to The Daunt'

[[action]]
text = 'Talk to Studious Vuadis'

[[action]]
text = 'On way to Chainscrape, make sure to find datapoint by burrower site'

[[action]]
location = 'Chainscrape'
text = 'Upgrade bow with acid arrows'
