title = "Mary-Beth's Fountain Pen"
start = "Horseshoe Overlook"
end = "Horseshoe Overlook"
type = 'item-request'
begin = "Speak to Mary-Beth when she is writing"

before = [
    'a-fisher-of-men',
]


[[post_action]]
text = "Get fountain pen for Mary-Beth from cabin"
location = 'Osman Grove'
after = ['penny-dreadful']  # same looting location

[[post_action]]
chained = true
text = "Give Mary-Beth fountain pen"
location = 'Horseshoe Overlook'
