title = "Jack's Penny Dreadful"
start = "Horseshoe Overlook"
end = "Horseshoe Overlook"
type = 'item-request'
autobegin = true


[[post_action]]
text = "Get penny dreadful for Jack from cabin"
location = "Osman Grove"

[[post_action]]
chained = true
text = "Give Jack penny dreadful"
location = 'Horseshoe Overlook'
