#!/bin/bash -euo pipefail

DEFAULT_SHOW='Horizon Zero Dawn'
show="$DEFAULT_SHOW"

function usage {
    sed -e 's/^        //' <<EOF
        Usage:

            ./generate [-n] [show] <command> [args]

                Runs <command> for the named [show], or the default show
                "$DEFAULT_SHOW" as configured in the generate script.

                -n  Perform a dry-run, only list what would be done.

            ./generate [command] help

                Show help text for the given command, or this script.

EOF
    exit 0
}

case "$1" in
    help) 
        usage
        ;;
    -n|--dry-run)
        export DRY_RUN=1
        shift
        ;;
esac

if [ "${2:-}" = 'help' ]; then
    cat bin/$1 \
        | awk '
            /bin.bash/{show=1; next}
            /^[^#]/{show=0}
            show
          ' \
        | sed -e '1d' -e '$d' -e 's/^#//' -e 's/^ //'
    exit 0
fi

if [ -d "$1" ]; then
    show="$1"
    shift
fi

export CAPTURE_DIR='Movies'
export CAPTURE_HOST='portsider'
export GAME_SHOW_NAME="$show"
export S3_BUCKET=gameshows.m17s.net
export S3_BUCKET_DIR="Game Shows/$show"
export THINGS_PROJECT=$(cat "$show/things.id")
export TV_HOST='southpaw'
export TV_LOCATION="/files/tv/$(echo "$show" | sed -e 's/ /\\ /g')/Season\ 1"

export PATH="$PWD/bin:$PATH"

pushd "$show" >/dev/null
exec "$@"
