title = "Alarm Antennas"
type = 'salvage'
location = 'Barren Light'

after = [
    'side-quest/the-burning-blooms',
]


begin = 'Talk to Larend to start salvage'

[[action]]
text = 'Collect the antennas and return them to Larend'
