title = "Barren Light Salvager"
type = 'salvage'
location = 'Barren Light'

unlocks = [
    'salvage/convoy-ambush',
]

after = [
    'side-quest/the-bristlebacks-end',
    'rebel-camp/eastern-lie',
]


begin = 'Speak to Larend to get the first salvage contract'
