title = "Colleague and Key"
type = 'salvage'
location = 'The Raintrace'

requires = [
    'salvage/mine-launchers',
]
unlocks = [
    'salvage/underwater-salvage',
    'salvage/reinforced-components',
]


begin = "Follow Warend's trail, get the mine launcher from the Thunderjaw, kill the Clamberjaws, get the key"

[[action]]
text = 'Retrun to Danur, defeat the rebels, give him the key'
