title = "Elusive Fanghorn"
type = 'salvage'
location = 'Barren Light'

requires = [
    'salvage/alarm-antennas',
    'salvage/scavengers',
]


begin = 'Chase down the Fanghorn'

[[action]]
text = 'Loot a circulator and drill horn from the nearby Lancehorns'

[[action]]
text = 'Return to Larend to finish his salvage'

[[post_action]]
location = 'Merchant'
text = 'Can sell the Impact Spike Thrower'
