title = "Missing Gear"
type = 'salvage'
location = 'The Greenswell'


begin = 'Investigate the shelter, get scrolls from the corpse near the Snapmaw'

[[action]]
text = 'Travel to the ruins, get the Relic'
