title = "A Soldier's March"
type = 'side-quest'
start = 'The Bulwark'
end = 'Sheerside Mountains'


begin = 'Speak to Jekkah'

[[action]]
text = 'Speak to Wekatta'
location = 'March of the Ten'

[[action]]
text = 'Start the climb, rescue Rokko from the Stalker'

[[action]]
text = 'Continue, rescue Penttoh from machines'

[[action]]
text = 'Kill the Frostclaw'

[[action]]
text = 'Glide back down, speak to Wekatta again'
