title = "A Tribe Apart"
type = 'side-quest'
start = 'Plainsong'
end = 'Somewhere'

begin = 'Speak to Emboh'

[[action]]
text = 'Speak to Jaxx'
location = "Stone's Echo"

[[action]]
text = 'Follow Jaxx to Eqgle squad, then continue to Riverwatch'
location = "Riverwatch"

[[action]]
text = 'Climb to the tower to get the war cache'

[[action]]
text = 'Kill the machines, then return to Eqgle squad in the cave'

[[post_action]]
text = 'Speak to Jaxx and Korreh again'
location = 'Plainsong'
after = [ 'story/seeds-of-the-past' ]
