title = "Blood for Blood"
type = 'side-quest'
start = 'The Memorial Grove'
end = 'Somewhere'

triggers = 'rebel-outpost/shining-wastes-south'
unlocks = [
    'side-quest/blood-for-blood-falls-edge',
]


begin = 'Speak to Dekka, follow her to the rebel outpost'

[[action]]
text = 'Kill the rebels, loot everything'

[[action]]
text = "Find where Nakalla was held, free her, agree to meet at Fall's Edge"
