title = "Boom or Bust"
type = 'side-quest'
start = 'Hidden Ember'
end = 'Stillsands'

unlocks = [
    'weapon/boomers-shredder-gauntlet',
]


begin = 'Speak to Delah, then follow her'


[[action]]
text = 'Kill the machines, and continue on'

[[action]]
text = 'Rescue Boomer from the machines'

[[action]]
text = "Kill the Shellsnapper with Boomer's new shredder gauntlet"


[[post_action]]
text = "Scan the datapoint at Delah and Boomer's old workshop"
location = 'Chainscrape'

[[post_action]]
text = 'Speak to Delah and Boomer again'
location = 'Hidden Ember'
