title = "Breaking Even"
type = 'side-quest'
start = 'Camp Nowhere'
end = 'Camp Nowhere'

finish_before = [
    'side-quest/boom-or-bust',
    'errand/broken-locks',
]


begin = 'Speak to Porguf'

[[action]]
text = 'Kill the smaller machines'
location = 'The Spinebreak'

[[action]]
text = 'Kill the rockbreaker'

[[action]]
text = 'Return to Porguf'
location = 'Camp Nowhere'