title = "Deep Trouble"
type = 'side-quest'
start = 'Chainscrape'
end = 'Crimson Narrows'

after = [
    'story/to-the-brink-end',
]

begin = 'Talk to Arnuf'

[[action]]
text = 'Speak to Korvend, enter the mine'
location = 'Crimson Narrows'

[[action]]
text = 'Rescue the miners'

[[action]]
text = 'Return to Korvend'

[[post_action]]
text = 'Check in with the rescued miners'
location = 'Chainscrape'
