title = "Drowned Hopes"
type = 'side-quest'
start = 'Carja Camp'
end = 'Carja Camp'


begin = 'Talk to Gendas and Rushavid'

[[action]]
text = 'Retrieve the three keys'

[[action]]
text = 'Get the blueprints, then return to the Carja'
