title = "Forbidden Legacy"
type = 'side-quest'
start = 'The Base'
end = 'Somewhere'


begin = 'Speak to Alva'

[[action]]
text = "Meet Alva at Legacy's Landfall"
location = "Legacy's Landfall"

[[action]]
text = 'Enter the ruin, kill the Slitherfang'

[[action]]
text = "Climb the building, find Leviathan's data"

[[post_action]]
text = 'Talk to Alva again'
location = 'The Base'

[[post_action]]
text = 'Can sell the Utaru Protector armour'
location = 'Hunter'
