title = "In the Fog"
type = 'side-quest'
start = "Tide's Reach"
end = 'Somewhere'

unlocks = [
    'weapon/sunhawk-shredder-gauntlet',
]


begin = 'Speak to Fenirra'

[[action]]
text = 'Travel to the camp, investigate with your Focus, follow the trail'

[[action]]
text = 'Kill the Clawstrider'

[[action]]
text = 'Follow Garokkah, killing the Stalkers'

[[action]]
text = 'Scan the memorial, retrieve the missing piece from the Clamberjaws'

[[action]]
text = "Return to Tide's Reach, speak to Fenirra again"
