title = "Lofty Ambitions"
type = 'side-quest'
location = 'Hidden Ember'

requires = [
    'story/hidden-ember',
]


begin = 'Talk to Morlund, go to Dunehollow, retrieve the burner'

[[action]]
text = 'Speak to Morlund again, go for a flight in the balloon'

[[action]]
text = 'Kill the machines, then the Stormbird'
