title = "Need to Know"
type = 'side-quest'
start = 'Camp Nowhere'
end = 'The Rot'

unlocks = [
    'weapon/lightning-hunter-bow',
]

requires = [
    'story/cradle-of-echoes',
]


begin = 'Talk to Talanah'

[[action]]
text = 'Meet Talanah north of Thornmarsh'
location = 'Thornmarsh'

[[action]]
text = 'Rescue Amadis from the Fireclaw'

[[action]]
text = 'Break into The Rot, kill the rebels and Tideripper, find Nessa'

[[post_action]]
text = 'Speak to Talanah and Milu again'
location = 'Barren Light'
