title = "Shadow in the West"
type = 'side-quest'
location = "Shadow's Reach"

unlocks = [
    'weapon/whisper-hunter-bow',
]

requires = [
    'story/opened-the-gate',
]

before = [
    'story/deaths-door',
]

begin = 'Eliminate the Eclipse guards outside the encampment, then talk to Yef'

[[action]]
text = 'Make your way around, getting the datapoint and whisper hunter bow'

[[action]]
text = 'Infiltrate the encampment, kill the guards and Longleg, get the datapoint'

[[action]]
text = 'Inside, rescue Utaru, ignore that datapoint for now'

[[action]]
text = 'Kill Vezreh and his pet Ravager, scan his datapoints, talk to Yef again'

[[action]]
text = 'Get the cell datapoint (should have been 5 in total) on the way out'

[[post_action]]
text = 'Talk to Conover again'
location = 'Barren Light'

[[post_action]]
text = 'Talk to Yef again'
location = 'Plainsong'
