title = "Shadow from the Past"
type = 'side-quest'
start = 'Barren Light'
end = 'Barren Light'

unlocks = [
    'side-quest/shadow-in-the-west',
]

before = [
    'story/the-embassy',
]
after = [
    'side-quest/the-bristlebacks',
]

begin = 'Talk to Conover and guard'

[[action]]
text = 'Go to the clearing, enter the tunnel, kill the Eclipse cultists'
location = "Straggler's Shade"

[[action]]
text = 'Scan the datapoint at the end of the tunnel'

[[action]]
text = 'Kill the lieutenant, then examine the corpse'

[[action]]
text = 'Return to Conover and exonerate him'
location = 'Barren Light'
