title = "Signal Spike"
type = 'side-quest'
start = 'Camp Nowhere'
end = 'Somewhere'

unlocks = [
    'weapon/spinthorn-spike-thrower',
]


begin = 'Speak to Corend to find out about Silga'

[[action]]
text = 'Help Silga kill machines, then climb the antenna'

[[action]]
text = 'Climb the tower in Scalding Spear to triangulate the signal'
location = 'Scalding Spear'

[[action]]
text = 'Climb the mountain above the base to triangulate the signal'
location = 'The Base'

[[action]]
text = 'Return to Silga, get the spike thrower'
