title = "The Deluge"
type = 'side-quest'
start = 'Scalding Spear'
end = 'Somewhere'


begin = 'Speak to Zokkah'

[[action]]
text = 'Speak to Natikka'
location = 'Bleeding Mark'

[[action]]
text = 'Rescue the group trapped in the tower'

[[action]]
text = 'Rescue the group up on the platform'

[[action]]
text = 'Rescue the group up in the cliffs'

[[action]]
text = 'Return to Natikka'

[[action]]
text = 'Rescue Kentokk from the Gouge'

[[post_action]]
text = 'Speak to Natikka again'
location = 'Memorial Grove'
