title = "The Roots That Bind"
type = 'side-quest'
start = 'Plainsong'
end = 'Riverhymn'

unlocks = [
    'weapon/kues-sharpshot-bow',
]

after = [
    'story/deaths-door',
]

before = [
    'story/the-dying-lands',
]


begin = 'Talk to Nel to find out about Riverhymn'

[[action]]
text = 'Take out the rebels, then speak to Kue'
location = 'Riverhymn'

[[action]]
text = 'Collect Metal Pods from the Drumroot'

[[action]]
text = 'Return to Kue, and talk to Nel at the flowerbed'
