title = "The Blood Choke"
type = 'side-quest'
start = 'Thornmarsh'
end = 'Somewhere'


begin = 'Speak to Atekka'

[[action]]
text = 'Climb up the red river to find the squad, kill the clamberjaws'

[[action]]
text = 'Continue up, kill the rebels and their Fireclaw'

[[action]]
text = 'Destroy the dam'

[[post_action]]
text = 'Can sell the Tenakth Reaver armour'
location = 'Hunter'
