title = "The Twilight Path"
type = 'side-quest'
start = 'Chainscrape'
end = "Twilight's Landing"

after = [
    # these are in the other direction, do them first
    'errand/a-dash-of-courage',
    'side-quest/deep-trouble',
]


begin = 'Talk to Petra, learn of the Shadow Carja refugees'

[[action]]
text = 'Talk to Tolland'
before = [
    # do the pit after talking to Petra and Tolland, but before setting out
    'melee-pit/chainscrape',
]

[[action]]
text = 'Deal with attacking machines, talk to Lokasha'
location = "Twilight's Landing"

[[action]]
text = 'Climb tower, find body of priest, return'

[[post_action]]
text = 'Talk to Petra again'
location = 'Chainscrape'

[[post_action]]
text = 'Talk to Lokasha again'
location = 'Chainscrape'
