title = "The Promontory"
type = 'side-quest'
start = 'Plainsong'
end = 'Summerwind'

begin = 'Overhear Fane, Kel, and Bree talking about Kalae'

[[action]]
text = 'Investigate the trail, kill the Stalkers'
location = 'The Promontory'

[[action]]
text = 'Return to Plainsong, talk to Bree and Fane'

[[action]]
text = 'Confront Kel, resolve Flashpoint (choose fist first so it is not the saved outcome)'
location = 'Summerwind'

[[post_action]]
text = 'Talk to Bree again'

[[post_action]]
text = 'Talk to Fane again'
