title = "The Twilight Path"
type = 'side-quest'
start = 'Chainscrape'
end = "Twilight's Landing"

begin = 'Talk to Petra, learn of the Shadow Carja refugees'

[[action]]
text = 'Deal with attacking machines, talk to Lokasha'
location = "Twilight's Landing"
after = [
    # these are in the other direction
    'errand/a-dash-of-courage',
    'side-quest/deep-trouble',
    'errand/a-bigger-boom',
]

[[action]]
text = 'Climb tower, find body of priest, return'

[[post_action]]
text = 'Talk to Petra again'
location = 'Chainscrape'

[[post_action]]
text = 'Talk to Lokasha again'
location = 'Chainscrape'
