title = "The Bristlebacks"
type = 'side-quest'
start = 'Chainscrape'
end = 'Chainscrape'

unlocks = [
    'side-quest/the-bristlebacks-end',
]

before = ['story/the-embassy']
after  = ['story/to-the-brink-end']

begin = 'Talk to Ulvund, and then Javad'

[[action]]
text = 'Head to the quarry, investigate the dead bristlebacks'
location = 'Redhew Quarry'
after = [
    # these are in the other direction
    'errand/a-dash-of-courage',
    'side-quest/deep-trouble',
    'errand/a-bigger-boom',
]

[[action]]
text = 'Enter Split Crag, kill more bristlebacks, find the datapoint'
location = 'Split Crag'

[[action]]
text = 'Return to Javad'
location = 'Chainscrape'
