title = "The Way Home"
type = 'side-quest'
start = "Legacy's Landfall"
end = 'Somewhere'

requires = [
    'story/the-wings-of-the-ten',   # need the sunwing to complete
]


begin = 'Speak to Harriem and Kristia'

[[action]]
text = 'Go to the shipwreck, find the gyrocompass, return to Harriem and Kristia'

[[action]]
text = 'Go to the ancient fleet, retrieve the broken sensor unit and batteries'

[[action]]
text = 'Go to the next location, kill the Dreadwing, collect the sensor unit'

[[action]]
text = 'Return to Harriem and Kristia'

# FIXME gets the Skykiller Spike Thrower
