title = "The Wound in the Sand"
type = 'side-quest'
start = 'Scalding Spear'
end = 'Somewhere'

unlocks = [
    'side-quest/the-gate-of-the-vanquished',
]


begin = 'Speak with Jetakka and Yarra'

[[action]]
text = 'Lead Yarra along the pipes to the pumping station'

[[action]]
text = 'Kill the machines'

[[action]]
text = 'Restore the pipe network'

[[post_action]]
text = 'Speak to Rakkar by the Wound, then head up to see Yarra and Drakka arguing'
location = 'Scalding Spear'
