title = "The Gate of the Vanquished"
type = 'side-quest'
location = 'Gemini'

unlocks = [
    'weapon/firestorm-warrior-bow',
]


begin = 'Listen to the arguments from both sides'

[[action]]
text = "Fight Drakka's men"

[[post_action]]
text = 'Speak to Yarra again'
location = 'Scalding Spear'
