title = "The Valley of the Fallen"
type = 'side-quest'
start = 'The Memorial Grove'
end = 'Valley of the Fallen'

requires = [
    'story/the-kulrut',
    'story/cradle-of-echoes',
]
unlocks = [
    'weapon/skystrike-boltblaster',
]


begin = 'Speak to Nakko'

[[action]]
text = 'Travel to the entry to the valley, speak to Ivvira and Kenalla'

[[action]]
text = 'Explore the valley, kill the patrolling machines'

[[action]]
text = 'Kill the Thunderjaw, Tremortusk, and Skydrifter'

[[action]]
text = 'Stop the Lure, find Yivekka'

[[action]]
text = 'Kill the Specters'

[[post_action]]
text = 'Speak to Nakko'
location = "Fall's Edge"
