title = "The Bristlebacks (End)"
type = 'side-quest'
start = 'Deadfalls'
end = 'Chainscrape'

requires = [
    'story/the-embassy',
]


begin = 'Sneak into the Deadfalls rebel outpost, kill everyone'

[[action]]
text = 'Make sure to loot the cache for the strongarm hunter bow'

[[action]]
text = 'Return and speak to Javad'
location = 'Chainscrape'

[[post_action]]
text = "Speak to Javad (in Ulvund's old building) and scan datapoint"
location = 'Chainscrape'

[[post_action]]
location = 'Merchant'
text = 'Can sell the Strongarm Hunter Bow'
