title = "The Burning Blooms"
type = 'side-quest'
start = "Stone's Echo"
end = 'The Spinebreak'

unlocks = [
    'side-quest/need-to-know',
]

begin = 'Talk to Mian, find out about Talanah'

[[action]]
text = 'Go to the area Talanah was headed, defeat the machines'

[[action]]
text = 'Follow Talanah, investigate the battlefield'

[[action]]
text = 'Defeat the Shellsnapper'

[[post_action]]
text = 'Check in on Milu'
location = "Stone's Echo"
