title = "The Second Verse"
type = 'side-quest'
start = 'The Base'
end = 'Somewhere'

unlocks = [
    'side-quest/the-second-verse-heal',
]


begin = 'Talk to Zo'

[[action]]
text = 'Meet Zo near the Memorial Grove'
location = 'The Memorial Grove'

[[action]]
text = 'Defeat the machines, speak to Zo again'
