title = "Thirst for the Hunt"
type = 'side-quest'
start = 'Arrowhand'
end = 'Arrowhand'

unlocks = [
    'side-quest/the-wound-in-the-sand',
]

after = [
    'story/hidden-ember',
]


begin = 'Speak to Drakka'

[[action]]
text = 'Follow Drakka, kill the machines for their hearts'

[[action]]
text = 'Follow Drakka again, kill the burrowers and Thunderjaw'

[[action]]
text = 'Return to Arrowhand, speak to Jetakka'

[[post_action]]
text = 'Speak to Drakka again'
