title = "What Was Lost"
type = 'side-quest'
start = 'The Base'
end = 'Ninmah Research Lab'

unlocks = [
    'side-quest/what-was-lost-testing-the-arm'
]


begin = 'Speak to Kotallo, learn about the arm'

[[action]]
text = 'Meet Kotallo, kill the machines, explore the research lab'
location = 'Ninmah Research Lab'

[[action]]
text = 'Kill the Specters'

[[action]]
text = 'Continue exploring, get the components needed'
