title = "Explosive Blastsling"
type = 'weapon'
start = 'Barren Light'
end = 'Workbench'

after = ['side-quest/shadow-from-the-past']

# 60 explosive / 24 purgewater, 50 build
begin = 'Purchase from Hunter for 149 shards and fanghorn circulator'

[[action]]
# 68 explosive / 27 purgewater, 61 build
text = 'Increase stats: 50 shards, 1 braided wire'
location = 'Workbench'

[[action]]
# 80 explosive / 33 purgewater, 74 build
text = 'Increase stats: 75 shards, 1 braided wire, 1 skydrifter circulator'

[[action]]
# 92 explosive / 37 purgewater, 92 build
text = 'Unlock coil, increase stats: 95 shards, 2 braided wire, 1 skydrifter razor tail, 1 small machine core'
