title = 'Hunter Bow'
type = 'weapon'
start = 'The Daunt'
end = 'The Daunt'
autobegin = true

unlocks = [
    'pouch/hunter-arrow-quiver',
]

[[action]]
text = 'Unlock acid arrows, increase stats: 50 shards, 1 braided wire'

[[action]]
text = 'Increase stats: 75 shards, 1 braided wire, 1 burrower circulator'
before = ['encounter/telga-fendur'] # upgrade early

[[action]]
text = 'Unlock coil, increase stats: 95 shards, 2 braided wire, 1 burrower soundshell, 1 small machine core'
# unlikely to get a soundshell before the previous upgrades, so do the
# rest of To The Brink first
after = ['story/to-the-brink-end']
