title = "Chainscrape Melee Pit"
type = 'melee-pit'
location = 'Chainscrape'

unlocks = [
    'errand/the-enduring',
]

after = [
    'side-quest/deep-trouble',
    'weapon/fire-hunter-bow',   # as it happened
]


begin = 'Learn about the Melee pits, learn combos, defeat Odurg'
