title = 'Chapter 6 -- Beaver Hollow'
type = 'marker'
start = 'Beaver Hollow'
end = 'Beaver Hollow'

unlocks = [
    # story
    'the-course-of-true-love-part-four',
    'money-lending-and-other-sins-part-six',
    'visiting-hours',

    # strangers
    'the-veteran',
]
