title = 'Money Lending and Other Sins VII'
type = 'story'
start = 'Beaver Hollow'
end = 'Beaver Hollow'
begin = "Return to camp, chuck Strauss out of the gang"

before = [
    'the-course-of-true-love-part-four',
]


leaves = [
    'strauss',
]
