title = 'Mrs Sadie Adler II'
type = 'story'
start = 'Hanging Dog Ranch'
end = 'Hanging Dog Ranch'
begin = "Find Sadie outside the ranch"

unlocks = [
    'my-last-boy',
]

before = [
    'the-bridge-to-nowhere',
]


[[action]]
text = "Kill the remaining O'Driscolls"

