title = 'The Course of True Love IV'
type = 'story'
start = 'Beaver Hollow'
end = 'Riggs Station'
begin = "Read a letter from Penelope Braithwaite"

before = [
    'just-a-social-call',
]


[[action]]
text = "Meet Penelope, and ride with her to Rhodes"
location = 'Braithwaite Manor'

[[action]]
text = "Beat up the Grays, shoot those following the train; then decline the bracelet"
