title = 'Visiting Hours'
type = 'story'
start = 'Copperhead Landing'
end = 'Beaver Hollow'
begin = "Meet Sadie at the dock and row to the penitentiary"

unlocks = [
    'just-a-social-call',
]

returns = [
    'john',
]

before = [
    'money-lending-and-other-sins-part-six',
    'the-course-of-true-love-part-four',
]


[[action]]
text = "Rescue John, do not kill the guard"

[[action]]
text = "While escaping by boat, watch for prisoners running for the shore"
