title = "The Stillsands Tallneck"
type = 'tallneck'
location = 'The Stillsands'

before = [
    'story/the-sea-of-sands',
]

after = [
    'side-quest/breaking-even',
]


begin = 'Explore the abandoned Oseram camp, examine the ballistas'

[[action]]
text = 'Kill the machines and use the ballistas to bring down and reboot the Tallneck'
