title = "The Stand of the Sentinels Tallneck"
type = 'tallneck'
location = 'The Stand of the Sentinels'


begin = 'Clear the area of Stalkers and Clamberjaws'

[[action]]
text = 'Climb the ruins of the settlement to get to the Tallneck'
