title = "Uncle's Bad Day"
type = 'story'
start = "Beecher's Hope"
end = "Beecher's Hope"
begin = "Go the barn, drink the night away"

unlocks = [
    'trying-again',
    'a-really-big-bastard',

    'the-past-is-gone',
]

returns = [
    'abigail',
    'jack',
]


[[action]]
text = "Rescue Uncle from the Skinners"
