title = "A Bigger Boom"
type = 'errand'
start = 'Chainscrape'
end = 'Chainscrape'

unlocks = [
    'weapon/prototype-spike-thrower',
    'side-quest/boom-or-bust',
]

after = [
    'melee-pit/chainscrape',
]


begin = 'Talk to Delah'

[[action]]
text = 'Gather 3 charger horns and a fanghorn rib'

[[action]]
text = 'Return and get the spike thrower'
