title = "A Dash of Courage"
type = 'errand'
start = 'Chainscrape'
end = 'Chainscrape'

unlocks = [
    'pouch/food-pouch',
]


begin = 'Talk to Milduf'

[[action]]
text = 'Gather 5 wild meat and 3 bitter leaf'

[[action]]
text = 'Gather a corrugated metal plate, making sure to get the upgrade parts needed from the Scroungers'
location = 'Scrounger Site'

[[action]]
text = 'Return to Milduf, get meal and buy two more for free'
