title = "A Hunt to Remember"
type = 'errand'
start = 'Cliffwatch'
end = 'The Stand of the Sentinels'


begin = 'Talk to Ikkotah, then go meet him at The Stand of the Sentinels'

[[action]]
text = 'Kill the machines, loot the bodies'

