title = "Broken Locks"
type = 'errand'
start = 'Camp Nowhere'
end = 'Somewhere'

requires = [
    'story/the-sea-of-sands',
    'side-quest/breaking-even',
]


begin = 'Speak to Porguf'

[[action]]
text = 'Speak to Petra'
location = 'Chainscrape'

[[action]]
text = 'Help Marsa'
location = 'The Daunt'

[[post_action]]
text = 'Speak to Marsa again'
location = 'Camp Nowhere'
