title = "Burden of Command"
type = 'errand'
start = 'Scalding Spear'
end = 'The Shining Wastes'

reqires = [
    'side-quest/the-gate-of-the-vanquished',
]


begin = 'Talk to Yarra'

[[action]]
text = 'Find the child, kill the Thunderjaw and Stormbird'
location = 'The Shining Wastes'
