title = "Call and Response"
type = 'errand'
start = 'The Bulwark'
end = 'Cold Rushes'


begin = 'Talk to Gerrah, learn of the squad'

[[action]]
text = 'Go to the watchtower, go check on Ezekko, kill the Skydrifters'

[[action]]
text = 'Return to the watchtower, kill the Glinthawks'
