title = "First to Fly"
type = 'errand'
location = 'The Bulwark'

requires = [
    'story/the-wings-of-the-ten',   # need the sunwing
]


begin = 'Talk to Serivva and Kettah'

[[action]]
text = 'Fly up to the mountaintop, pick up the armour'

[[action]]
text = 'Kill the Stormbird'

[[action]]
text = 'Return to the Bulwark, return the armour'
