title = "In Bloom"
type = 'errand'
start = 'The Shining Wastes'
end = 'The Shining Wastes'

requires = [
    'story/the-kulrut',
]


begin = 'Tak to Darikka and Teikka, collect three flowers'

[[action]]
text = 'Speak to the herbalist'
location = 'Plainsong'

[[action]]
text = 'Talk to Jia'
location = 'Riverhymn'

[[action]]
text = 'Return to Darikka and Teikka, tell them Nilo has died'
location = 'The Shining Wastes'
