title = "Opening the Arena"
type = 'errand'
location = 'Memorial Grove'


begin = 'Talk to Dukkah and Kalla'

[[action]]
text = 'Get two Bristleback tusks'

[[action]]
text = 'Get a Rollerback sinew'

[[action]]
text = 'Return to the grove'
