title = "Shining Example"
type = 'errand'
start = 'Arrowhand'
end = 'Stillsands'


begin = 'Talk to Marallo'

[[action]]
text = 'Fetch a Horus Energy Cell, drop it on the machines, kill the machines'

[[action]]
text = 'Kill the Dreadwing, loot the Greenshine'
