title = "Signals of the Sun"
type = 'errand'
start = 'Barren Light'
end = 'Barren Light'

begin = 'Come across Maleev north of Barren Light'

[[action]]
text = 'Rescue Raynah from the machines'

[[action]]
text = 'Gather the Lens of Evening from the signal tower above'

[[action]]
text = 'Return the lens to Raynah in Barren Light'

[[post_action]]
text = 'Gather the other lenses'
