title = "Supply Drop"
type = 'errand'
location = "Runner's Wild"


begin = 'Help Vetteh kill a Rollerback'

[[action]]
text = 'Speak to Vetteh, go find Littay'

[[action]]
text = 'Kill the machines, speak to Littay and Vetteh again'
