title = "The Oldgrowth"
type = 'errand'
start = 'Plainsong'
end = 'Somewhere'


begin = 'Speak to Shael, then Ven below'

[[action]]
text = 'Follow the tracks, killing machines along the way'
location = 'Oldgrowth'

[[action]]
text = 'Speak to Lao'

[[action]]
text = 'Return the seed pouches to Shael'
location = 'Plainsong'

[[post_action]]
text = 'Speak to Lao and Ven again'
location = 'Plainsong'
