title = "The Enduring"
type = 'errand'
location = 'The Greenswell'

requires = [
    'melee-pit/chainscrape',
    'melee-pit/scalding-spear',
    'melee-pit/the-bulwark',
    'melee-pit/thornmarsh',
]


begin = 'Speak to Azurekka, fight Azurekka, get upgraded spear'
