title = "The Taste of Victory"
type = 'errand'
location = 'Salt Bite'


begin = 'Talk to the cook'

[[action]]
text = 'From the island, collect bird meat and eggs, also killing the Widemaw'

[[action]]
text = 'Return to the cook, get free meals'
