title = "The Music in Metal"
type = 'errand'
start = 'Plainsong'
end = 'Plainsong'

requires = [
    'side-quest/a-tribe-apart',
]


begin = 'Speak to Jaxx and Korreh'

[[action]]
text = 'Meet Jaxx, kill the machines'

[[action]]
text = 'Follow Jaxx, kill the machines, then talk to Jaxx again'
location = 'Whitewatch Peaks'

[[action]]
text = 'Return to Plainsong and give Korreh the longleg throat'
