title = "Tides of Justice"
type = 'errand'
start = "Tide's Reach"
end = 'Somewhere'


requires = [
    'story/the-wings-of-the-ten',
]

begin = 'Speak to Cragella and Davvoh'

[[action]]
text = 'Fly to the island, speak to Ivvalla'

[[action]]
text = 'Fly to the raiders, kill them'
