title = "Castor's Ridge"
start = "Castor's Ridge"
end = "Castor's Ridge"
type = 'location'
autobegin = true


[[action]]
text = "Watch the farmer and sons putting up the house"

[[action]]
text = "Rescue the farmer from extortionists"

[[action]]
text = "Help the farmer get some lumber"
after = ['appleseed-timber_1']  # to get the lumber for free…
before = ['appleseed-timber_3'] # …but they still need to be there

[[action]]
text = "Say goodbye to the farmer, who has sold up"
