title = "Oseram Delvers"
type = 'encounter'
location = "No Man's Land Relic Ruin"


begin = 'Fight the Tenakth rebels attacking the Oseram'

before = [
    'cauldron/mu',
    'tallneck/cinnabar-sands',
    'salvage/convoy-ambush',
]

after = [
    'side-quest/the-bristlebacks-end',
    'salvage/barren-light',
]
