title = 'A Quiet Time'
type = 'story'
start = 'Horseshoe Overlook'
end = 'Valentine'
begin = "One evening before sunset, talk to Dutch at his tent"

unlocks = [
    'blessed-are-the-meek',
    'a-fisher-of-men',

    # lenny's item request
    'pocket-watch',

    # activity
    'five-finger-fillet-with-lenny',
]

returns = [
    'lenny',
]

before = [
    'money-lending-and-other-sins-part-three',
    'paying-a-social-call',
    'pouring-forth-oil-part-one',
    'we-loved-once-and-true-part-one',
]


[[action]]
text = "Take Lenny to Valentine for a drink"
location = 'Valentine'

[[action]]
text = "Catch Lenny in the act when searching for the third time"
