title = 'Chapter 2 -- Horseshoe Overlook'
type = 'marker'
start = 'Horseshoe Overlook'
end = 'Horseshoe Overlook'

unlocks = [
    # story
    'americans-at-rest',
    'polite-society-valentine-style',
    'who-is-not-without-sin',

    # stranger missions
    'a-fisher-of-fish',
    'a-test-of-faith',
    'american-dreams',
    'arcadia-for-amateurs-part-one',
    'fundraiser-part-one',
    'geology-for-beginners',
    'smoking-and-other-hobbies',
    'the-noblest-of-men-and-a-woman-part-one',

    # item requests
    'book',
    'five-dollars',
    'fountain-pen',
    'pipe',
    'poison-knives',
    'rabbit',
    'thimble',

    # activities
    'hunt-bison',
    'rob-chez-porter',

    # treasure maps
    'all-that-glitters',
    'landmarks-of-riches',

    # other
    'appleseed-timber',
    'beaver-tooth-trinket',
    'buck-antler-trinket',
    'camp-chores',
    'camp-supplies',
    'castors-ridge',
    'cat-eye-trinket',
    'elk-antler-trinket',
    'hawk-talon-trinket',
    'loot-crashed-train',
    'railroad-camp',
    'replenish-supplies',
    'return-to-camp',
    'speech-notes',
    'weapon-care',
]
