title = 'Paying a Social Call'
type = 'story'
start = 'Horseshoe Overlook'
end = 'Six Point Cabin'
begin = 'One morning, talk to Kieran'

unlocks = [
    'we-loved-once-and-true-part-one',
    'pouring-forth-oil-part-one',
]


[[action]]
text = "Follow Kieran to Six Point Cabin, kill some O'Driscolls, escape the law"

[[post_action]]
text = "Read about shotgun in journal"
location = 'Horseshoe Overlook'
