title = 'Pouring Forth Oil III'
type = 'story'
start = 'Horseshoe Overlook'
end = 'The Heartlands'
begin = "Speak to John, refresh your weapons and go meet the gang"

unlocks = [
    'the-sheep-and-the-goats',
    'an-american-pastoral-scene',

    # dead eye level 2
]

before = [
    'blessed-are-the-meek',
]


[[action]]
text = "Block the train tracks, rob the train, kill the law, escape"
