title = 'Arcadia for Amateurs'
type = 'stranger'
start = 'Lagras'
end = 'Lagras'
begin = "Help Mason photograph some alligators"

unlocks = [
    'arcadia-for-amateurs-part-five',
]

after = ['chapter-3']
before = ['the-artists-way_1']  # so Mason's pictures are in the gallery
