title = 'The Noblest of Men, and a Woman (Flaco Hernandez)'
start = 'Cairn Lake'
end = 'Cairn Lake'
type = 'stranger'
begin = "Clean out gang members, duel Flaco Hernandez, take photo"

unlocks = [
    'poisonous-trail',  # find the map at the same time
    'arabian',          # see the horse on the way back
]
