title = 'The Noblest of Men, and a Woman I'
start = 'Valentine'
end = 'Valentine'
type = 'stranger'
begin = "Enter Keane's Saloon, meet Theodore Levin"

unlocks = [
    'black-belle',
    'emmet-granger',
    'flaco-hernandez',
    'billy-midnight',
]

after = [
    # should have been to valentine already
    'polite-society-valentine-style',
]
before = [
    # do it before shooting Valentine up
    'the-sheep-and-the-goats',
]
