title = 'START THE GAME'
type = 'border'
start = 'start'
end = 'Far Zenith'

autobegin = true
triggers = 'story/reach-for-the-stars'

reminders = [
    'reminder/time',
    'reminder/skill-points',
    'reminder/resources',
    'reminder/recording',
]

completed_threads = [
    # ch1+2
    'story/reach-for-the-stars',

]

# notes:
# * when marking a thread as partially complete, remember to list all
#   completed nodes in the thread, not just the latest
# * completed threads don't mark post_actions as complete
completed_nodes = [
]

abandoned_threads = [
]

abandoned_nodes = [
]
