title = 'START THE GAME'
type = 'border'
start = 'start'
end = 'Far Zenith'

autobegin = true
triggers = 'story/reach-for-the-stars'

reminders = [
    'reminder/time',
    'reminder/skill-points',
    'reminder/resources',
    'reminder/recording',
]

completed_threads = [
    # ch1+2
    'story/reach-for-the-stars',

    # ch3
    'story/the-point-of-the-lance',
    'weapon/hunter-bow',
    'story/to-the-brink',
    'encounter/telga-fendur',

    # ch4
    'story/to-the-brink-erend',
    'story/to-the-brink-end',

    # ch5
    'errand/a-dash-of-courage',
    'side-quest/deep-trouble',
    'weapon/fire-hunter-bow',
    'melee-pit/chainscrape',

    # ch6
    'side-quest/the-twilight-path',

]

# notes:
# * when marking a thread as partially complete, remember to list all
#   completed nodes in the thread, not just the latest
# * completed threads don't mark post_actions as complete
completed_nodes = [
    # ch3
    'weapon/frost-blastsling_0',
    # 'story/to-the-brink-erend_0',

    # ch5
    'weapon/shock-tripcaster_0',
    'weapon/shock-tripcaster_1',
    'pouch/resource-pouch_0',
    'side-quest/the-twilight-path_0',

    # ch6
    'errand/a-bigger-boom_0',
    'side-quest/the-bristlebacks_0',
    'side-quest/the-bristlebacks_1',

]

abandoned_threads = [
]

abandoned_nodes = [
]
