title = "Plainsong Hunting Ground"
type = 'hunting-ground'
start = 'Plainsong'
end = 'Plainsong Hunting Ground'

after = [
    'story/deaths-door',                # don't go near Plainsong until met Zo
    'side-quest/the-roots-that-bind',
]

unlocks = [
    'weapon/sun-touched-hunter-bow',
]


begin = 'Talk to Ivinna to learn of the hunting ground'

[[action]]
text = 'Talk to the groundskeeper'
location = 'Plainsong Hunting Ground'

[[action]]
text = 'Complete the Silent Looting Trial (ensure to get Tracker Burrower circulator)'

[[action]]
text = 'Complete the Silent Strike Trial'

[[action]]
text = 'Complete the Silent Gliding Trial'
