title = "Sheerside Mountains Hunting Ground"
type = 'hunting-ground'
location = 'Sheerside Mountains'

after = [
    'weapon/boomers-shredder-gauntlet',     # where we first learn shredders
    'hunting-ground/the-raintrace',         # uses the glowblast sharpshot bow
]


begin = 'Speak to Lokattok'

[[action]]
text = 'Complete the Frost Trial'

[[action]]
text = 'Complete the Shredder Catch Trial'

[[action]]
text = 'Complete the Plasma Blast Trial'
