title = "The Daunt Hunting Ground"
type = 'hunting-ground'
start = 'The Daunt Hunting Ground'
end = 'The Daunt Hunting Ground'

unlocks = [
    'weapon/fire-hunter-bow',
    'weapon/shock-warrior-bow',
    'weapon/ropecaster',
]

after = [
    'side-quest/the-twilight-path',
]

begin = 'Talk to the groundskeeper, buy the Strike pieces and weapons'

[[action]]
text = 'Complete the Tear Trial'

[[action]]
text = 'Complete the Shock Trial'

[[action]]
text = 'Complete the Shock and Trap Trial'
