title = "The Raintrace Hunting Ground"
type = 'hunting-ground'
location = 'The Raintrace'

unlocks = [
    'weapon/glowblast-sharpshot-bow',
]


begin = 'Purchase the Glowblast Sharpshot bow'

[[action]]
text = 'Complete the Shock and Remove Trial'

[[action]]
text = 'Complete the Mounted Combat Trial'

[[action]]
text = 'Complete the Heavy Weapons Trial'
