title = "Jagged Deep rebel outpost"
type = 'rebel-outpost'
location = 'Jagged Deep'

begin = 'Kill the riders carefully when approaching'

[[action]]
text = 'Take out the rebels in the outpost, careful of Aloy dialogue about taking parts from the Corruptors'
