title = "Plainsong rebel outpost"
type = 'rebel-outpost'
location = 'Plainsong rebel outpost'

after = [
    'story/deaths-door',    # don't go near Plainsong until met Zo
    'hunting-ground/plainsong',
]


begin = 'Kill the rebels'
