title = "Plainsong rebel outpost"
type = 'rebel-outpost'
start = 'Plainsong'
end = 'Plainsong rebel outpost'

after = [
    'story/deaths-door',    # don't go near Plainsong until met Zo
]

begin = 'Get the rumour about the outpost'

[[action]]
text = 'Kill the rebels'
location = 'Plainsong Rebel Outpost'
