title = "The High Turning rebel outpost"
type = 'rebel-outpost'
location = 'The High Turning'

requires = [
    'story/the-eye-of-the-earth',   # just a barrier before restoring Gaia
]


begin = 'Take out the rebels'
