title = "Rob Lonnie's Shack"
start = 'Clemens Point'
end = "Lonnie's Shack"
type = 'activity'
begin = "One morning, talk to Sean"

finish_before = [
    'blessed-are-the-peacemakers',
]


[[action]]
text = "Rob Lonnie's Shack, don't kill the last outlaw"
