title = 'American Distillation'
type = 'story'
start = 'Scarlett Meadows'
end = 'Clemens Point'
begin = "Speak to Dutch in the Sheriff's office"

unlocks = [
    'an-honest-mistake',
    'advertising-the-new-american-art',

    # stranger
    'no-good-deed',
]

before = [
    'further-questions-of-female-suffrage',
    'the-course-of-true-love-part-one',
]


[[action]]
text = "Accompany the wagon"

[[action]]
text = "Kill the moonshiners"

[[action]]
text = "Win the race back to camp"
