title = 'Magicians for Sport'
type = 'story'
start = 'Clemens Point'
end = 'Rhodes'
begin = "One morning, Arthur speaks to dutch about bounty hunters"

unlocks = [
    'friends-in-very-low-places',
    'blessed-are-the-peacemakers',
]

before = [
    'the-fine-joys-of-tobacco',
    'an-honest-mistake',
    'the-course-of-true-love-part-three',
]


[[action]]
text = "Investigate Trelawny's caravan, interrogate the men"

[[action]]
text = "Kill the bounty hunters, taking care to loot them and get the rare sniper rifle"
