title = 'The Course of True Love III'
type = 'story'
start = 'Caliga Hall'
end = 'Bolger Glade'
begin = 'Speak to Beau'

unlocks = [
    'the-course-of-true-love-part-four',
]


[[action]]
text = "Sneak into Braithwaite Manor, give Penelope letter and gift"
