title = "Cauldron Chi"
type = 'cauldron'
location = 'Southern Lowlands'

unlocks = [
    'override/stalker',
    'override/shellsnapper',
    'override/spikesnout',
    'override/scorcher',
    'override/fireclaw',
]


begin = 'Find the original entrance, then find the other way in'

[[action]]
text = 'Advance through the cauldron to the core, killing the machines'

[[action]]
text = 'Kill the Slitherfang, override the core'
