title = "Cauldron Iota"
type = 'cauldron'
location = 'Salt Bite'

unlocks = [
    'override/bellowback',
    'override/ravager',
    'override/rollerback',
    'override/skydrifter',
    'override/snapmaw',
]


begin = 'Approach the cauldron, then find the crevice to get in'

[[action]]
text = 'Advance through the cauldron to the core, killing the machines'

[[action]]
text = 'Repair and override the Tallneck to exit'
