title = "Cauldron Kappa"
type = 'cauldron'
location = 'North of The Greenhouse'

unlocks = [
    'override/dreadwing',
    'override/slaughterspine',
    'override/slitherfang',
    'override/thunderjaw',
]


begin = 'Kill the Shellsnapper and Snapmaw guarding the entrance'

[[action]]
text = 'Advance through the cauldron to the core, killing the machines'

[[action]]
text = 'Kill the Tideripper, override the core'
