title = "Mu"
type = 'cauldron'
start = 'Cauldron Mu'
end = 'Cauldron Mu'

unlocks = [
    'override/fanghorn',
    'override/scrapper',
    'override/widemaw',
]

before = [
    'side-quest/shadow-in-the-west',
]

after = [
    'salvage/convoy-ambush',
]


begin = 'Advance through the cauldron to the core, killing the machines'

[[action]]
text = 'Kill the two widemaws'
