title = "Bomb Satchel"
type = 'pouch'
location = 'Workbench'


autobegin = true

[[action]]
text = 'Increase carry capacity: 25 shards, 1 boar bone'

[[action]]
text = 'Increase carry capacity: 50 shards, 3 vulture feather'
after = ['story/the-eye-of-the-earth']  # not found in the daunt or plainsong

[[action]]
text = 'Increase carry capacity: 100 shards, 3 owl feather, 1 salmon bone'

[[action]]
text = 'Increase carry capacity: 200 shards, 3 lobster shell, 1 iridescent crab shell, 1 peccary bone'
