title = "Hunter Arrow Quiver"
type = 'pouch'
location = 'Workbench'


autobegin = true

[[action]]
text = 'Increase carry capacity: 25 shards, 2 raccoon hide'

[[action]]
text = 'Increase carry capacity: 50 shards, 1 rabbit hide, 1 peccary bone'
after = ['story/restored-gaia']  # not found in the daunt or plainsong

[[action]]
text = 'Increase carry capacity: 100 shards, 3 bighorn sheep skin, 1 salmon bone'

[[action]]
text = 'Increase carry capacity: 200 shards, 1 pelican wishbone, 2 peccary hide, 1 iridescent lobster shell'
