title = "Precision Arrow Quiver"
type = 'pouch'
location = 'Workbench'


autobegin = true

[[action]]
text = 'Increase carry capacity: 50 shards, 1 fox bone'

[[action]]
text = 'Increase carry capacity: 100 shards, 1 vulture wishbone, 1 horned lizard skin'
after = ['story/restored-gaia']  # not found in the daunt or plainsong

[[action]]
text = 'Increase carry capacity: 200 shards, 3 moonfish skin, 1 owl wishbone'

[[action]]
text = 'Increase carry capacity: 300 shards, 3 bass skin, 1 moonfish bone, 1 iridescent lobster shell'
