title = "Breached Rock rebel camp"
type = 'rebel-camp'
location = 'Breached Rock'


begin = 'Enter the camp, kill the rebels, take the key'

[[action]]
text = 'Enter the bunker, kill the rebels, examine the device, overload the batteries'
