title = "Eastern Lie"
type = 'rebel-camp'
location = 'Eastern Lie'

begin = 'Enter carefully via the river'

[[action]]
text = 'Kill the rebels, explode the blaze, rescue the prisoner'

[[post_action]]
text = 'Can sell the Carja Blazon armour'
location = 'Hunter'
