title = "Fenrise rebel camp"
type = 'rebel-camp'
location = 'Fenrise'


begin = 'Kill some rebels, talk to the Tenakth who come to assist'

[[action]]
text = 'Kill the radar (with a strikethrough arrow to kill the rebel too)'

[[action]]
text = 'Kill the remaining rebels, examine the parchment and ornamentation'

[[action]]
text = 'Kill the reinforcements rebels that turn up, speak to Gattak'
