title = "First Forge"
type = 'rebel-camp'
start = 'The Base'
end = 'First Forge'

unlocks = [
    'weapon/the-sun-scourge',
]

requires = [
    'rebel-camp/breached-rock',
    'rebel-camp/devils-grasp',
    'rebel-camp/eastern-lie',
    'rebel-camp/fenrise',
    'rebel-camp/the-hive',
]


begin = 'Talk to Erend about the Sons of Prometheus'

[[action]]
text = 'Infiltrate the First Forge'
location = 'First Forge'

[[action]]
text = 'Kill Asera'

[[post_action]]
text = 'Speak to Erend about Asera (get damage coil)'
location = 'The Base'
