title = "The Hive rebel camp"
type = 'rebel-camp'
start = 'The Base West exit'
end = 'The Hive'

unlocks = [
    'weapon/piercing-sharpshot-bow',
]

after = [
    'gauntlet-run/dry-yearn',
]


begin = 'Get the rumour about the rebel camp'

[[action]]
text = 'Kill the rebels, explode the weapon caches, rescue the prisoner'
